# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-02 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_permission_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(max_length=64),
        ),
    ]
